name: Infrastructure Management (PowerShell)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      action:
        description: 'Action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - validate

env:
  AZURE_LOCATION: eastus

jobs:
  set-environment:
    name: 'Set Environment Variables'
    runs-on: ubuntu-latest
    outputs:
      resource-group: ${{ steps.env.outputs.resource-group }}
      frontend-app: ${{ steps.env.outputs.frontend-app }}
      backend-app: ${{ steps.env.outputs.backend-app }}
      parameters-file: ${{ steps.env.outputs.parameters-file }}
      app-service-sku: ${{ steps.env.outputs.app-service-sku }}
    steps:
      - name: Set environment variables
        id: env
        run: |
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "resource-group=rg-prodigy1-prod" >> $GITHUB_OUTPUT
            echo "frontend-app=prodigy1-prod-webapp" >> $GITHUB_OUTPUT
            echo "backend-app=prodigy1-prod-funcapp" >> $GITHUB_OUTPUT
            echo "parameters-file=parameters.prod.json" >> $GITHUB_OUTPUT
            echo "app-service-sku=S1" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "resource-group=rg-prodigy1-staging" >> $GITHUB_OUTPUT
            echo "frontend-app=prodigy1-staging-webapp" >> $GITHUB_OUTPUT
            echo "backend-app=prodigy1-staging-funcapp" >> $GITHUB_OUTPUT
            echo "parameters-file=parameters.dev.json" >> $GITHUB_OUTPUT
            echo "app-service-sku=B1" >> $GITHUB_OUTPUT
          else
            echo "resource-group=rg-prodigy1-dev" >> $GITHUB_OUTPUT
            echo "frontend-app=prodigy1-dev-webapp" >> $GITHUB_OUTPUT
            echo "backend-app=prodigy1-dev-funcapp" >> $GITHUB_OUTPUT
            echo "parameters-file=parameters.dev.json" >> $GITHUB_OUTPUT
            echo "app-service-sku=F1" >> $GITHUB_OUTPUT
          fi

  validate-infrastructure:
    name: 'Validate Infrastructure'
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PowerShell
        shell: bash
        run: |
          # Install PowerShell
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Install Azure PowerShell
        shell: pwsh
        run: |
          Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser
          Import-Module Az

      - name: Validate Bicep template
        run: |
          echo "🔍 Validating Bicep template for ${{ github.event.inputs.environment }} environment..."
          
          # Test Bicep compilation
          bicep build infrastructure/bicep/main.bicep --outfile /tmp/main.json
          echo "✅ Bicep template compiled successfully"
          
          # Test CORS config template too
          bicep build infrastructure/bicep/cors-config.bicep --outfile /tmp/cors-config.json
          echo "✅ CORS config template compiled successfully"
          
          # Show the compiled template size and basic info
          echo "📊 Template information:"
          echo "Main template size: $(wc -c < /tmp/main.json) bytes"
          echo "CORS template size: $(wc -c < /tmp/cors-config.json) bytes"
          
          echo "✅ Template validation completed successfully"

      - name: Estimate costs
        run: |
          echo "💰 Estimating costs for ${{ github.event.inputs.environment }} environment..."
          echo "Resource Group: ${{ needs.set-environment.outputs.resource-group }}"
          echo "App Service SKU: ${{ needs.set-environment.outputs.app-service-sku }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

  deploy-infrastructure:
    name: 'Deploy Infrastructure'
    runs-on: ubuntu-latest
    needs: [set-environment, validate-infrastructure]
    if: github.event.inputs.action == 'deploy'
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PowerShell
        shell: bash
        run: |
          # Install PowerShell
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Install Azure PowerShell
        shell: pwsh
        run: |
          Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser
          Import-Module Az

      - name: Create Resource Group
        shell: pwsh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          $clientSecret = "${{ secrets.AZURE_CLIENT_SECRET }}" | ConvertTo-SecureString -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential("${{ secrets.AZURE_CLIENT_ID }}", $clientSecret)
          Connect-AzAccount -ServicePrincipal -Credential $credential -TenantId "${{ secrets.AZURE_TENANT_ID }}" -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          
          Write-Host "🏗️ Creating resource group: ${{ needs.set-environment.outputs.resource-group }}"
          $rg = New-AzResourceGroup -Name "${{ needs.set-environment.outputs.resource-group }}" -Location "${{ env.AZURE_LOCATION }}" -Tag @{"Environment"="${{ github.event.inputs.environment }}"; "Project"="Prodigy1"} -Force
          Write-Host "✅ Resource group created successfully"

      - name: Deploy Infrastructure
        shell: pwsh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          chmod +x ./deploy-with-powershell.ps1
          ./deploy-with-powershell.ps1
